name: numbercrunching
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flutter_tex: ^3.6.7+8
  cloud_firestore: ^0.13.7
  url_launcher: ^5.5.0
  youtube_player_flutter: ^7.0.0+7
  flutter_rating_bar: ^3.0.1+1
  image: ^2.0.7
  animator: 0.1.4
#  image_picker: ^0.6.4
  image_picker: ^0.6.7+4
  google_sign_in: ^4.0.1+1
  timeago: 2.0.17
  cached_network_image:
  firebase_auth: ^0.16.1
  geolocator: 5.0.1
  uuid: ^2.0.0
  path_provider: ^0.5.0+1
  firebase_messaging: ^4.0.0+1
  firebase_storage: ^3.1.5
  device_info: ^0.4.2+4


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/json/
    - assets/images/google_signin_button.png
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
        - asset: assets/fonts/Signatra.ttf
        - asset: assets/fonts/Rubik-Italic.ttf
          style: italic
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 300
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 100
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 300
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
